# Generated by Django 5.2.3 on 2025-07-31 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('inquiry_type', models.CharField(choices=[('general', '일반 문의'), ('product', '제품 문의'), ('other', '기타 문의')], default='general', max_length=20, verbose_name='문의 유형')),
                ('message', models.TextField(verbose_name='문의 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='문의일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '문의',
                'verbose_name_plural': '문의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=450, unique=True, verbose_name='제품 고유 코드')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('description', models.TextField(verbose_name='제품 설명')),
                ('category', models.CharField(max_length=50, verbose_name='제품 카테고리')),
                ('is_active', models.BooleanField(default=True, verbose_name='판매 활성화 여부')),
                ('is_export', models.BooleanField(default=False, verbose_name='수출용 제품 여부')),
                ('sort_order', models.IntegerField(default=0, verbose_name='화면 표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('image_type', models.CharField(choices=[('main', 'Main'), ('detail', 'Detail'), ('package', 'Package'), ('label', 'Label'), ('certificate', 'Certificate')], max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='glossymatcha.products')),
            ],
            options={
                'verbose_name': '제품 이미지',
                'verbose_name_plural': '제품 이미지',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_key', models.CharField(max_length=100, verbose_name='스펙 항목명')),
                ('spec_value', models.CharField(max_length=255, verbose_name='스펙 값')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='glossymatcha.products')),
            ],
            options={
                'verbose_name': '제품 상세 설명',
                'verbose_name_plural': '제품 상세 설명',
                'ordering': ['created_at'],
            },
        ),
    ]
