# Generated by Django 5.2.4 on 2025-08-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('offline_sales', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='오프라인 매출')),
                ('other_sales', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='기타 매출')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '일별 매출',
                'verbose_name_plural': '일별 매출',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('inquiry_type', models.CharField(choices=[('general', '일반 문의'), ('product', '제품 문의'), ('other', '기타 문의')], default='general', max_length=20, verbose_name='문의 유형')),
                ('message', models.TextField(verbose_name='문의 내용')),
                ('message_en', models.TextField(blank=True, verbose_name='문의 내용 (영어)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='문의일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '문의',
                'verbose_name_plural': '문의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='제품명 (영어)')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='제품 부제목')),
                ('subtitle_en', models.CharField(blank=True, max_length=300, verbose_name='제품 부제목 (영어)')),
                ('description', models.TextField(verbose_name='제품 설명')),
                ('description_en', models.TextField(blank=True, verbose_name='제품 설명 (영어)')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='슬로건')),
                ('short_description_en', models.CharField(blank=True, max_length=500, verbose_name='슬로건 (영어)')),
                ('sub_description', models.TextField(blank=True, verbose_name='제품 부가 설명')),
                ('sub_description_en', models.TextField(blank=True, verbose_name='제품 부가 설명 (영어)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='제품 보증 문구')),
                ('note_en', models.CharField(blank=True, max_length=200, verbose_name='제품 보증 문구 (영어)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='직원명')),
                ('nickname', models.CharField(max_length=50, verbose_name='영어 닉네임')),
                ('employee_type', models.CharField(choices=[('full_time', '정직원'), ('part_time', '파트타임')], max_length=20, verbose_name='근무 형태')),
                ('hire_date', models.DateField(verbose_name='입사일')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('resident_number', models.CharField(max_length=13, verbose_name='주민번호')),
                ('contact', models.CharField(max_length=20, verbose_name='연락처')),
                ('memo', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '직원',
                'verbose_name_plural': '직원',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('contact_person', models.CharField(max_length=50, verbose_name='담당자')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('payment_method', models.CharField(choices=[('cash', '현금'), ('transfer', '계좌이체'), ('card', '카드'), ('credit', '외상')], max_length=20, verbose_name='결제방식')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='거래 중')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YearlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='연도')),
                ('total_material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간 총 재료비')),
                ('total_labor_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간 총 노무비')),
                ('total_supplies_expense', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간 총 경비-소모품')),
                ('total_other_expense', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간 총 경비-기타')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '년별 매출',
                'verbose_name_plural': '년별 매출',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('alt_text_ko', models.CharField(blank=True, max_length=100, verbose_name='이미지 설명 (한국어)')),
                ('alt_text_en', models.CharField(blank=True, max_length=100, verbose_name='이미지 설명 (영어)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='glossymatcha.products', verbose_name='제품')),
            ],
            options={
                'verbose_name': '제품 이미지',
                'verbose_name_plural': '제품 이미지',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=450, verbose_name='제품 고유 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='glossymatcha.products', verbose_name='제품')),
            ],
            options={
                'verbose_name': '제품 상세 설명',
                'verbose_name_plural': '제품 상세 설명',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('month', models.PositiveIntegerField(verbose_name='월')),
                ('material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='재료비')),
                ('labor_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='노무비')),
                ('supplies_expense', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='경비-소모품')),
                ('other_expense', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='경비-기타')),
                ('inventory_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='재고금액')),
                ('actual_usage_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='실 사용금액')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '월별 매출',
                'verbose_name_plural': '월별 매출',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='총 근무시간')),
                ('hourly_rate', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='시급')),
                ('monthly_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='월급')),
                ('weekly_holiday_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='주휴수당')),
                ('total_payment', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='지급합계')),
                ('memo', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='glossymatcha.staff', verbose_name='직원')),
            ],
            options={
                'verbose_name': '급여 기록',
                'verbose_name_plural': '급여 기록',
                'ordering': ['-created_at'],
            },
        ),
    ]
