# Generated by Django 5.2.4 on 2025-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('offline_sales', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='오프라인 매출')),
                ('other_sales', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='기타 매출')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '일별 매출',
                'verbose_name_plural': '일별 매출',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='YearlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='연도')),
                ('total_material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간 총 재료비')),
                ('total_labor_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간 총 노무비')),
                ('total_supplies_expense', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간 총 경비-소모품')),
                ('total_other_expense', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='연간 총 경비-기타')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '년별 매출',
                'verbose_name_plural': '년별 매출',
                'ordering': ['-year'],
            },
        ),
        migrations.RemoveField(
            model_name='sales',
            name='offline_sales',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='other_sales',
        ),
    ]
