# Generated by Django 5.2.4 on 2025-08-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='note',
        ),
        migrations.RemoveField(
            model_name='products',
            name='note_en',
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='제품 안내사항'),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='제품 안내사항 (영어)'),
        ),
    ]
