# Generated by Django 5.2.3 on 2025-07-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_export',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(blank=True, max_length=450, null=True, unique=True, verbose_name='제품 고유 코드'),
        ),
    ]
