# Generated by Django 5.2.4 on 2025-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0002_dailysales_yearlysales_remove_sales_offline_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='연락처'),
        ),
    ]
