# Generated by Django 5.2.4 on 2025-08-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0002_remove_products_note_remove_products_note_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='pay_period_weeks',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3, verbose_name='급여 기간(주)'),
        ),
    ]
