# Generated by Django 5.2.4 on 2025-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0003_alter_suppliers_email_alter_suppliers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='message_en',
            field=models.TextField(blank=True, verbose_name='문의 내용 (영어)'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='이미지 설명 (영어)'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='alt_text_ko',
            field=models.CharField(blank=True, max_length=100, verbose_name='이미지 설명 (한국어)'),
        ),
        migrations.AddField(
            model_name='products',
            name='category_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='제품 카테고리 (영어)'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='제품 설명 (영어)'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='제품명 (영어)'),
        ),
        migrations.AddField(
            model_name='productspecifications',
            name='spec_key_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='스펙 항목명 (영어)'),
        ),
        migrations.AddField(
            model_name='productspecifications',
            name='spec_value_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='스펙 값 (영어)'),
        ),
    ]
