# Generated by Django 5.2.4 on 2025-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0003_workrecord_pay_period_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiries',
            name='message',
            field=models.TextField(blank=True, verbose_name='문의 내용'),
        ),
    ]
