# Generated by Django 5.2.3 on 2025-08-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0004_alter_inquiries_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiries',
            name='message_en',
        ),
        migrations.AlterField(
            model_name='inquiries',
            name='message',
            field=models.TextField(verbose_name='문의 내용'),
        ),
    ]
