# Generated by Django 5.2.4 on 2025-08-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0004_inquiries_message_en_productimages_alt_text_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ['-created_at'], 'verbose_name': '제품 이미지', 'verbose_name_plural': '제품 이미지'},
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='productspecifications',
            name='spec_key',
        ),
        migrations.RemoveField(
            model_name='productspecifications',
            name='spec_key_en',
        ),
        migrations.RemoveField(
            model_name='productspecifications',
            name='spec_value',
        ),
        migrations.RemoveField(
            model_name='productspecifications',
            name='spec_value_en',
        ),
        migrations.AddField(
            model_name='products',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='제품 보증 문구'),
        ),
        migrations.AddField(
            model_name='products',
            name='note_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='제품 보증 문구 (영어)'),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='슬로건'),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='슬로건 (영어)'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_description',
            field=models.TextField(blank=True, verbose_name='제품 부가 설명'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_description_en',
            field=models.TextField(blank=True, verbose_name='제품 부가 설명 (영어)'),
        ),
        migrations.AddField(
            model_name='products',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='제품 부제목'),
        ),
        migrations.AddField(
            model_name='products',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='제품 부제목 (영어)'),
        ),
        migrations.AddField(
            model_name='productspecifications',
            name='product_code',
            field=models.CharField(blank=True, max_length=450, verbose_name='제품 고유 코드'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='glossymatcha.products', verbose_name='제품'),
        ),
        migrations.AlterField(
            model_name='productspecifications',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='glossymatcha.products', verbose_name='제품'),
        ),
    ]
