# Generated by Django 5.2.4 on 2025-08-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0005_remove_inquiries_message_en_alter_inquiries_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, verbose_name='제품 설명'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='제품명'),
        ),
    ]
