# Generated by Django 5.2.4 on 2025-08-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0006_alter_products_description_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='영어 닉네임'),
        ),
    ]
