# Generated by Django 5.2.4 on 2025-08-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0007_alter_staff_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['resignation_date', 'employee_type', 'name'], 'verbose_name': '직원', 'verbose_name_plural': '직원'},
        ),
        migrations.AddField(
            model_name='staff',
            name='original_employee_type',
            field=models.CharField(blank=True, choices=[('full_time', '정직원'), ('part_time', '파트타임'), ('resigned', '퇴사')], max_length=20, null=True, verbose_name='원래 근무 형태'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_type',
            field=models.CharField(choices=[('full_time', '정직원'), ('part_time', '파트타임'), ('resigned', '퇴사')], max_length=20, verbose_name='근무 형태'),
        ),
    ]
