# Generated by Django 5.2.3 on 2025-08-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0008_alter_staff_options_staff_original_employee_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '일별 비밀번호',
                'verbose_name_plural': '일별 비밀번호',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['resignation_date', 'employee_type', 'hire_date', 'name'], 'verbose_name': '직원', 'verbose_name_plural': '직원'},
        ),
    ]
