# Generated by Django 5.2.3 on 2025-08-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossymatcha', '0009_dailypassword_alter_staff_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPassword',
        ),
    ]
